# Simple and useful Pytorch functions


In this notebook I'll describe some useful Pytorch functions. 



*   torch.rand()
*   unfold(dimension, size, step) → Tensor
*   torch.transpose()
*   std_mean()
*   torch.inverse()








Before we begin, let's install and import PyTorch

In [49]:
# Import torch and other required modules
import torch

## Function 1 - torch.rand ()

Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)

The shape of the tensor is defined by the variable argument size.

In [50]:
# Example 1 
torch.rand(10)

tensor([0.9458, 0.6378, 0.7915, 0.8656, 0.0322, 0.2377, 0.2829, 0.9904, 0.9975,
        0.0840])

In this example we use the torch.rand () function to create a one-dimensional tensor with 10 random elements between 0 to 1.

In [51]:
# Example 2 - working
torch.rand(4, 3)

tensor([[0.3252, 0.2117, 0.9975],
        [0.4390, 0.1001, 0.6663],
        [0.7925, 0.7118, 0.4381],
        [0.9549, 0.9133, 0.4492]])

In this case, we create a 4
-row, 3-column tensor with random elements between 0 and 1.

In [52]:
# Example 3 - breaking 

torch.rand(-1)

RuntimeError: ignored

The function fails if we try to create a tensor with non-coherent dimensions.

The torch.rand () function is very useful for creating tensors in a simple and fast way.

Let's save our work using Jovian before continuing.

In [53]:
!pip install jovian --upgrade --quiet

In [54]:
import jovian

In [55]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arunkumar68330/01-tensor-operations


'https://jovian.ai/arunkumar68330/01-tensor-operations'

## unfold(dimension, size, step) → Tensor

Returns a view of the original tensor which contains all slices of size size from self tensor in the dimension dimension.



In [56]:
# Example 1 - working
x = torch.arange(10., 39)

x.unfold(0, 3, 4)

tensor([[10., 11., 12.],
        [14., 15., 16.],
        [18., 19., 20.],
        [22., 23., 24.],
        [26., 27., 28.],
        [30., 31., 32.],
        [34., 35., 36.]])

We've created an array from 10 to 38. Then we unfold it with number of items per array of 3. Between each array; the step is four, therefore the first item of each array will be the first item of the previous array plus 4.

In [57]:
# Example 2 - working

x = torch.arange(10., 39)
x.unfold(0, 6, 10)


tensor([[10., 11., 12., 13., 14., 15.],
        [20., 21., 22., 23., 24., 25.],
        [30., 31., 32., 33., 34., 35.]])

 Each array has 6 items and the difference (step) between the first items of each array is 10

In [58]:
# Example 3 - breaking (to illustrate when it breaks)

x = torch.tensor([[1., 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]])
x.unfold(0, 4, 2)


RuntimeError: ignored

The size is bigger than the number of arrays at the Tensor "x" (there are only 3 arrays in the tenso

when to use this function Use this function to slice a Tensor controlling the size of the output.

In [59]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arunkumar68330/01-tensor-operations


'https://jovian.ai/arunkumar68330/01-tensor-operations'

## Function 3 - torch.transpose()

Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

The resulting out tensor shares it’s underlying storage with the input tensor, so changing the content of one would change the content of the other.



In [60]:
# Example 1 - working

x = torch.randn(1, 2)
print("x = " ,x)

print(" \n transpose = ",torch.transpose(x, 0, 1))


x =  tensor([[-0.3341,  0.6199]])
 
 transpose =  tensor([[-0.3341],
        [ 0.6199]])


In the example above, with the help of the torch.transpose() function we are obtaining the transpose of a row vector, converting it into a column vector, dimensions 0 and 1 are interchanged.


In [61]:
# Example 2 - working
x = torch.randn(2, 2)
print("x = " ,x)


y = torch.transpose(x, 0, 1)
print("y = " ,y)



x =  tensor([[ 0.2615,  1.0808],
        [ 0.4682, -0.3177]])
y =  tensor([[ 0.2615,  0.4682],
        [ 1.0808, -0.3177]])


In this example we obtain the transpose of a 2x2 matrix, exchanging the dimensions 0 and one. The rows become columns and the columns become rows.


In [62]:
# Example 3 - breaking 

torch.transpose(x, 0, 2)


IndexError: ignored

The function fails if we don't work with the right dimensions.

This function is very useful when we are dealing with common problems in the field of linear algebra.

In [63]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arunkumar68330/01-tensor-operations


'https://jovian.ai/arunkumar68330/01-tensor-operations'

## Function 4 - torch.std_mean()

Add some explanations Returns the standard-deviation and mean of all elements in the input tensor.



In [64]:
# Example 1 - working
x = torch.randn(8,8,8) # Let's create a randon Tensor size (8,8,8)

torch.std_mean(x)


(tensor(0.9927), tensor(-0.0693))

Explanation about example Standard Deviaton and mean is displayed considering all elements of the tensor "x"

In [65]:
# Example 2 - working
x = torch.randn(2,2)
print("x = ",x)

print(" std_mean = ",torch.std_mean(x))


x =  tensor([[ 0.1885,  0.5517],
        [-1.1257,  0.1995]])
 std_mean =  (tensor(0.7390), tensor(-0.0465))


Explanation about example Another Tensor with it's SD and Mean displayed.

In [66]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.randn(3, 2)
torch.std_mean(x, 2)


IndexError: ignored

Explanation about example The dimension of range is lower than requested. We could add a third dimension to the Tensor "x" and the errour should be gone. Otherwise, we could just keep in between the range established in the error message.

Simple but powerful function to be able to know your Tensor while working.

In [67]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arunkumar68330/01-tensor-operations


'https://jovian.ai/arunkumar68330/01-tensor-operations'

## Function 5 - torch.inverse()

Takes the inverse of the square matrix input. input can be batches of 2D square tensors, in which case this function would return a tensor composed of individual inverses.

In [68]:
# Example 1 - working
x = torch.rand(2, 2)
print("x = ",x)


y = torch.inverse(x)
print("y = ",y)


z = torch.mm(x, y)
print("z = ",z)



x =  tensor([[0.9605, 0.5244],
        [0.5575, 0.8476]])
y =  tensor([[ 1.6244, -1.0049],
        [-1.0684,  1.8407]])
z =  tensor([[1.0000e+00, 0.0000e+00],
        [5.9605e-08, 1.0000e+00]])


In the example above we calculate the inverse of a 2x2 matrix and check the result by multiplying the matrix by its inverse so that we obtain a diagonal matrix.


In [69]:
# Example 2 - working

x = torch.rand(9).reshape(3,3)
print("x = ",x)

y = torch.inverse(x)
print("y = ",y)

z = torch.mm(x, y)
print("z = ",z)



x =  tensor([[0.8468, 0.1394, 0.8268],
        [0.5885, 0.0223, 0.8642],
        [0.8578, 0.1945, 0.7311]])
y =  tensor([[ 23.9667,  -9.2954, -16.1176],
        [-49.1042,  14.2289,  38.7150],
        [-15.0560,   7.1207,   9.9785]])
z =  tensor([[ 1.0000e+00, -3.4453e-07, -1.2693e-07],
        [ 5.2019e-07,  1.0000e+00, -2.4647e-07],
        [ 4.6261e-07,  3.3441e-07,  1.0000e+00]])


Computation of a inverse of 3x3 matrix



In [70]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.arange(9).reshape(3,3)
print("x = " ,x)

y = torch.inverse(x)
print("y = " ,y)


x =  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


RuntimeError: ignored

The computation of inverse matrix fails if the matrix is ​​singular, as in this example, there is a correlation between the rows of the matrix.




The computation of the inverse of a matrix is ​​essential if we are dealing with topics that involve linear algebra.

In [45]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arunkumar68330/01-tensor-operations


'https://jovian.ai/arunkumar68330/01-tensor-operations'

In this short notebook we have described some simple but at the same time useful pytorch functions, especially when working on topics involving linear algebra.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [47]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arunkumar68330/01-tensor-operations


'https://jovian.ai/arunkumar68330/01-tensor-operations'